name: Billing-App

on:
  pull_request:
    types: [closed]
    branches:
      - devops # Trigger workflow when a pull request to the 'devops' branch is closed
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  merge_with_ci_skip:
    if: github.actor == 'Santhosh-Nagaraja' && github.event.pull_request.merged == true # Run this job only if a pull request is merged and contains '[ci skip]' in the commit message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Terraform Init
        working-directory: ./client-folder
        run: terraform init

      - name: Terraform Format
        working-directory: ./client-folder
        run: terraform fmt

      - name: Terraform Validation
        working-directory: ./client-folder
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./client-folder
        run: terraform plan
     

  merge_without_ci_skip:
    if: github.actor == 'Santhosh-Nagaraja' && github.event.pull_request.merged == true && !contains(github.event.pull_request.head_commit.message, '[ci skip]') # Run this job only if a pull request is merged and does not contain '[ci skip]' in the commit message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.6   # Specify the desired Terraform version

      - name: Terraform Init
        working-directory: ./develop-folder
        run: terraform init
      
      - name: Terraform Format
        working-directory: ./develop-folder
        run: terraform fmt
         
      - name: Terraform Validation
        working-directory: ./develop-folder
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./develop-folder
        run: terraform plan
