name: Conditional Jobs

on:
  pull_request:
    types: [closed]
    branches:
      - devops # Trigger workflow when a pull request to the 'devops' branch is closed
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  check-commit-message:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    outputs:
      skip_job: ${{ steps.check.outputs.skip_job }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Get merge commit message
        id: get_commit_message
        run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Check commit message
        id: check
        run: |
          if [[ "${{ env.message }}" == *"skip the job"* ]]; then
            echo "skip_job=true" >> $GITHUB_ENV
          else
            echo "skip_job=false" >> $GITHUB_ENV
          fi

  first-job:
    needs: check-commit-message
    if: ${{ needs.check-commit-message.outputs.skip_job == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Terraform Init
        working-directory: ./client-folder
        run: terraform init

      - name: Terraform Format
        working-directory: ./client-folder
        run: terraform fmt

      - name: Terraform Validation
        working-directory: ./client-folder
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./client-folder
        run: terraform plan

  second-job:
    needs: check-commit-message
    if: ${{ needs.check-commit-message.outputs.skip_job == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.6   # Specify the desired Terraform version

      - name: Terraform Init
        working-directory: ./develop-folder
        run: terraform init
      
      - name: Terraform Format
        working-directory: ./develop-folder
        run: terraform fmt
         
      - name: Terraform Validation
        working-directory: ./develop-folder
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./develop-folder
        run: terraform plan
