name: Billing-App

on:
  pull_request:
    types: [closed]
    branches:
      - devops # Trigger workflow when a pull request to the 'devops' branch is closed
  workflow_dispatch: # Allow manual triggering of the workflow
  push:
    branches:
      - devops # Trigger workflow on push events to the 'devops' branch

jobs:
  merge_job:
    if: github.event.pull_request.merged == true # Run this job only if a pull request is merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge Job
        run: echo "This job runs on merge events." # Indicate job runs on merge events

  push_job:
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[ci skip]') # Run job on push events excluding specific commit messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.6   # Specify the desired Terraform version

      - name: Terraform Init
        working-directory: ./client-folder
        run: terraform init
      
      - name: Terraform Format
        working-directory: ./client-folder
        run: terraform fmt
         
      - name: Terraform Validation
        working-directory: ./client-folder
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./client-folder
        run: terraform plan
