name: Conditional Jobs

on:
  pull_request:
    types: [closed]
    branches:
      - release # Trigger workflow when a pull request to the 'release' branch is closed
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  check-commit-message:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    outputs:
      skip_job: ${{ steps.check.outputs.skip_job }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get merge commit message
        id: get_commit_message
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"
    
      - name: Check commit message
        id: check
        run: |
          if [[ "${{ steps.get_commit_message.outputs.message }}" == *"skip the job"* ]]; then
            echo "::set-output name=skip_job::true"
          else
            echo "::set-output name=skip_job::false"

  first-job:
    needs: check-commit-message
    if: ${{ needs.check-commit-message.outputs.skip_job == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Terraform Init
        working-directory: ./client-folder
        run: terraform init

      - name: Terraform Format
        working-directory: ./client-folder
        run: terraform fmt

      - name: Terraform Validation
        working-directory: ./client-folder
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./client-folder
        run: terraform plan

  second-job:
    needs: check-commit-message
    if: ${{ needs.check-commit-message.outputs.skip_job == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.6   # Specify the desired Terraform version

      - name: Terraform Init
        working-directory: ./develop-folder
        run: terraform init
      
      - name: Terraform Format
        working-directory: ./develop-folder
        run: terraform fmt
         
      - name: Terraform Validation
        working-directory: ./develop-folder
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./develop-folder
        run: terraform plan
