name: CI Pipeline

on:
  push:
    branches:
      - '**'  # Triggers on any push
  pull_request:
    types:
      - closed  # Triggers on merge event

jobs:
  merge_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Job
        run: echo "This job runs on merge events."

  push_job:
    if: github.event.pull_request.merged != true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push Job
        run: echo "This job runs on push events."
