name: Billing-App

on:
  pull_request:
    types: [closed]
    branches:
      - devops
  workflow_dispatch:
  push:
    branches:
      - devops

env:
    image_version: ${{ github.run_number }}
 
jobs:
  terraform:
    if:
      github.event.pull_request.merged == true
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5
 
      - name: Echo
        run: echo "hello world"
 
     
      
  send-job:
    if: github.event_name == 'push' && needs.first-job.outputs.skip == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run second job steps
        run: |
          echo "Running steps in the second job..."
          # Add your steps here
